### ISSUE TITLE
I'm using the mime-wrapper in Angular 7, getting can't find module error

### ISSUE THREAD

**Issue by benyusouf** [marlon360/mime-wrapper#2]
could not find a declaration file for module 'mime-wrapper'. in.................

**Comment by marlon360** [comment]
I do not experience any issues with Angular 7.

Could you provide the full error log for better investigation?

**Comment by benyusouf** [comment]
Could not find a declaration file for module 'mime-wrapper'. 'c:/Users/.../Client/node_modules/mime-wrapper/index.js' implicitly has an 'any' type.
  Try `npm install @types/mime-wrapper` if it exists or add a new declaration (.d.ts) file containing `declare module 'mime-wrapper';`ts(7016)
Could not find a declaration file for module 'mime-wrapper'. `'c:/Users/.../node_modules/mime-wrapper/index.js'` implicitly has an 'any' type.
  Try `npm install @types/mime-wrapper` if it exists or add a 


@marlon360  I was getting this tslint error on vs code. However, everything is working fine on the actual application. Thank you

**Comment by marlon360** [comment]
Okay, thank you.
I think I will add a Type Definition file to avoid this warning.

**Comment by marlon360** [comment]
I added the Type Definitions.
Now you should not get any errors with tslint.

@benyusouf Could you confirm, that the new version is working without any warnings?

**Comment by benyusouf** [comment]
@marlon360  Yes I just updated it and no more warnings, thank you
